# Generated by Django 6.0.3 on 2026-03-21 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='descuento',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Descuento (%)'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='¿Destacar en el Banner de Ofertas?'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Original'),
        ),
    ]
